[package]
name = "conquer-queue"
version = "0.1.0"
authors = ["Oliver Giersch <oliver.giersch@b-tu.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reclaim = { git = "https://github.com/oliver-giersch/reclaim" }